# This is a basic workflow to help you get started with Actions

name: runner-mock-update-canary
on:
  [workflow_dispatch, workflow_call]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
